import React from 'react';
import Link from 'next/link'; // Provides client-side navigation between routes
import { Inter } from 'next/font/google'; // Imports the Inter font from Google Fonts

import './globals.css'; // Global CSS styles for the application

import TooltipProvider from "@/components/TooltipProvider";

// Load the Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] });

/**
 * Metadata object
 * 
 * Defines metadata for the application, including the title and description.
 * This metadata can be used by the Next.js framework for SEO purposes.
 */
export const metadata = {
  title: 'Buckets App', // The title of the application
  description: 'Generated by create next app', // A brief description of the app
};

/**
 * RootLayout Component
 * 
 * This component defines the root layout of the application.
 * It wraps all pages with a consistent HTML structure, global font, and layout styles.
 * 
 * Props:
 * - `children`: ReactNode representing the content of the current page.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // The content to render inside the layout
}>) {
  const backToMain = process.env.NEXT_PUBLIC_MAIN_SITE_URL || '/';
  return (
    <html lang="en">
      {/* Include Google's GSI Client library for authentication */}
      <script src="https://accounts.google.com/gsi/client" async defer></script>

      <body className={inter.className}>
        <header className="flex items-center justify-between px-6 py-3 border-b border-zinc-800 bg-black text-white">
          <Link href="/bracket" className="font-semibold">
            Bracket Builder
          </Link>
          <Link href={backToMain} className="text-sm text-blue-300 hover:text-blue-200">
            Back to Main Site
          </Link>
        </header>
        {/**
         * Main Content Area:
         * - The `children` prop represents the content of the current page being rendered.
         * - It is wrapped with padding for consistent spacing.
         */}
        <main className="p-4 h-[calc(100vh-64px)] bg-zinc-950 text-white">
          <TooltipProvider></TooltipProvider>
          {children}
        </main>
      </body>
    </html>
  );
}
