import React from 'react';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Buckets App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script src="https://accounts.google.com/gsi/client" async defer></script>
      <body className={inter.className}>
        <nav className="bg-gray-800 p-4">
          <ul className="flex space-x-4">
            <li><Link href="/"><a className="text-white hover:underline">Home</a></Link></li>
            <li><Link href="/about"><a className="text-white hover:underline">About</a></Link></li>
            <li><Link href="/contact"><a className="text-white hover:underline">Contact</a></Link></li>
          </ul>
        </nav>
        <main className="p-4">
          {children}
        </main>
      </body>
    </html>
  );
}